# Generated by Django 5.0.3 on 2024-03-31 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('handicap', models.IntegerField(default=0)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('no_of_tournaments', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='play',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf.player'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
