# Generated by Django 5.0.3 on 2024-03-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
