# Generated by Django 5.0.3 on 2024-03-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_remove_player_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='play',
            unique_together={('player', 'tournament')},
        ),
    ]
